In [28]:
from pandas_datareader import data
import datetime

In [15]:
data.DataReader?

In [37]:
from pandas_datareader import data
import datetime
from bokeh.plotting import figure,show,output_file
from bokeh.embed import components
from bokeh.resources import CDN

start = datetime.datetime(2020,11,1)
end = datetime.datetime.now()
df = data.DataReader(name="GOOG",data_source="yahoo",start=start,end=end)
df

,High,Low,Open,Close,Volume,Adj Close
Date,,,,,,
2020-11-02,1660.770020,1616.030029,1628.160034,1626.030029,2535400,1626.030029
2020-11-03,1661.699951,1616.619995,1631.780029,1650.209961,1661700,1650.209961
2020-11-04,1771.364990,1706.030029,1710.280029,1749.130005,3570900,1749.130005
2020-11-05,1793.640015,1750.510010,1781.000000,1763.369995,2065800,1763.369995
2020-11-06,1772.430054,1740.349976,1753.949951,1761.750000,1660900,1761.750000
...,...,...,...,...,...,...
2021-02-01,1922.391968,1850.930054,1853.569946,1901.349976,1602200,1901.349976
2021-02-02,1955.760010,1914.489990,1922.560059,1927.510010,2273700,1927.510010
2021-02-03,2116.500000,2018.380005,2073.000000,2070.070068,4118200,2070.070068
2021-02-04,2078.550049,2042.589966,2068.889893,2062.370117,1851100,2062.370117
2021-02-05,2102.510010,2059.330078,2070.000000,2098.000000,1533900,2098.000000

In [24]:
def win_los(c,o):
    if c > o:
        value = "win"
    elif c < o: 
        value = "lose"
    else:
        value = "equal"
    return value

df["Status"] = [win_los(c,o) for c,o in zip(df.Close,df.Open)]
df["Middle"] = (df.Open+df.Close) /2
df["Height"] = abs(df.Open-df.Close)

df

,High,Low,Open,Close,Volume,Adj Close,Status,Middle,Height
Date,,,,,,,,,
2020-11-02,1660.770020,1616.030029,1628.160034,1626.030029,2535400,1626.030029,lose,1627.095032,2.130005
2020-11-03,1661.699951,1616.619995,1631.780029,1650.209961,1661700,1650.209961,win,1640.994995,18.429932
2020-11-04,1771.364990,1706.030029,1710.280029,1749.130005,3570900,1749.130005,win,1729.705017,38.849976
2020-11-05,1793.640015,1750.510010,1781.000000,1763.369995,2065800,1763.369995,lose,1772.184998,17.630005
2020-11-06,1772.430054,1740.349976,1753.949951,1761.750000,1660900,1761.750000,win,1757.849976,7.800049
...,...,...,...,...,...,...,...,...,...
2021-02-01,1922.391968,1850.930054,1853.569946,1901.349976,1602200,1901.349976,win,1877.459961,47.780029
2021-02-02,1955.760010,1914.489990,1922.560059,1927.510010,2273700,1927.510010,win,1925.035034,4.949951
2021-02-03,2116.500000,2018.380005,2073.000000,2070.070068,4118200,2070.070068,lose,2071.535034,2.929932
2021-02-04,2078.550049,2042.589966,2068.889893,2062.370117,1851100,2062.370117,lose,2065.630005,6.519775
2021-02-05,2102.510010,2059.330078,2070.000000,2098.000000,1533900,2098.000000,win,2084.000000,28.000000

In [25]:
win = df.index[df.Status == "win"]
lose = df.index[df.Status == "lose"]

middle_win = df.Middle[df.Status == "win"]
middle_lose = df.Middle[df.Status == "lose"]

height_win = df.Height[df.Status == "win"]
height_lose = df.Height[df.Status == "lose"]
'''
for date in win:
    print(date)
print("\n")    
for date in lose:
    print(date)
'''

'\nfor date in win:\n    print(date)\nprint("\n")    \nfor date in lose:\n    print(date)\n'

In [46]:
p = figure(x_axis_type="datetime",width = 1000, height = 300,sizing_mode="scale_width")

# Styling
p.title.text = "Candlestick Chart"
p.grid.grid_line_alpha = 0.3

# segment(heightX,heightY,lowX,lowY)
p.segment(df.index,df.High,df.index,df.Low,color="black")

# p.rect(x,y,width,height)
hours_12 = 12 * 60 * 60 * 1000
p.rect(win,middle_win, hours_12,
       height_win,line_color="black",fill_color="#CCFFFF")

p.rect(lose,middle_lose, hours_12,
        height_lose,line_color="black",fill_color="#FF3333")



#output_file('stock_graph.html')
#show(p)

# Live Url 
# components is a tuple 
jscript,div1 = components(p)
cdn_js = CDN.js_files
cdn_css = CDN.css_files

print(cdn_js[0])

https://cdn.bokeh.org/bokeh/release/bokeh-2.2.3.min.js