In [28]:
from pandas_datareader import data
import datetime

In [15]:
data.DataReader?

In [2]:
from pandas_datareader import data
import datetime
from bokeh.plotting import figure,show,output_file

start = datetime.datetime(2021,1,1)
end = datetime.datetime.now()
df = data.DataReader(name="GOOG",data_source="yahoo",start=start,end=end)
df

,High,Low,Open,Close,Volume,Adj Close
Date,,,,,,
2021-01-04,1760.650024,1707.849976,1757.540039,1728.239990,1901900,1728.239990
2021-01-05,1747.670044,1718.015015,1725.000000,1740.920044,1145300,1740.920044
2021-01-06,1748.000000,1699.000000,1702.630005,1735.290039,2602100,1735.290039
2021-01-07,1788.400024,1737.050049,1740.060059,1787.250000,2265000,1787.250000
2021-01-08,1809.839966,1773.535034,1787.979980,1807.209961,2050600,1807.209961
2021-01-11,1794.314941,1760.520020,1786.069946,1766.719971,1209700,1766.719971
2021-01-12,1778.040039,1725.310059,1753.920044,1746.550049,1357700,1746.550049
2021-01-13,1765.035034,1738.010010,1738.579956,1754.400024,1094100,1754.400024
2021-01-14,1775.010010,1733.400024,1753.619995,1740.180054,1179500,1740.180054
2021-01-15,1756.000000,1721.550049,1738.189941,1736.189941,1328300,1736.189941
2021-01-19,1809.275024,1741.459961,1752.250000,1790.859985,1734600,1790.859985
2021-01-20,1903.709961,1825.530029,1831.459961,1886.900024,2490300,1886.900024
2021-01-21,1934.859985,1887.109985,1898.000000,1891.250000,2063900,1891.250000
2021-01-22,1910.949951,1881.760010,1895.680054,1901.050049,1272100,1901.050049
2021-01-25,1929.579956,1867.530029,1920.670044,1899.400024,1927300,1899.400024
2021-01-26,1925.000000,1884.244995,1888.839966,1917.239990,1313100,1917.239990
2021-01-27,1890.000000,1809.000000,1882.530029,1830.790039,2748300,1830.790039
2021-01-28,1898.829956,1842.640015,1843.939941,1863.109985,1773100,1863.109985
2021-01-29,1857.280029,1810.199951,1846.170044,1835.739990,1612600,1835.739990
2021-02-01,1922.391968,1850.930054,1853.569946,1901.349976,1602200,1901.349976
2021-02-02,1955.760010,1914.489990,1922.560059,1927.510010,2273700,1927.510010
2021-02-03,2116.500000,2018.380005,2073.000000,2070.070068,4118200,2070.070068
2021-02-04,2078.550049,2042.589966,2068.889893,2062.370117,1851100,2062.370117
2021-02-05,2102.510010,2059.330078,2070.000000,2098.000000,1533900,2098.000000

In [3]:
def win_los(c,o):
    if c > o:
        value = "win"
    elif c < o: 
        value = "lose"
    else:
        value = "equal"
    return value

df["Status"] = [win_los(c,o) for c,o in zip(df.Close,df.Open)]
df["Middle"] = (df.Open+df.Close) /2
df["Height"] = abs(df.Open-df.Close)

df

,High,Low,Open,Close,Volume,Adj Close,Status,Middle,Height
Date,,,,,,,,,
2021-01-04,1760.650024,1707.849976,1757.540039,1728.239990,1901900,1728.239990,lose,1742.890015,29.300049
2021-01-05,1747.670044,1718.015015,1725.000000,1740.920044,1145300,1740.920044,win,1732.960022,15.920044
2021-01-06,1748.000000,1699.000000,1702.630005,1735.290039,2602100,1735.290039,win,1718.960022,32.660034
2021-01-07,1788.400024,1737.050049,1740.060059,1787.250000,2265000,1787.250000,win,1763.655029,47.189941
2021-01-08,1809.839966,1773.535034,1787.979980,1807.209961,2050600,1807.209961,win,1797.594971,19.229980
2021-01-11,1794.314941,1760.520020,1786.069946,1766.719971,1209700,1766.719971,lose,1776.394958,19.349976
2021-01-12,1778.040039,1725.310059,1753.920044,1746.550049,1357700,1746.550049,lose,1750.235046,7.369995
2021-01-13,1765.035034,1738.010010,1738.579956,1754.400024,1094100,1754.400024,win,1746.489990,15.820068
2021-01-14,1775.010010,1733.400024,1753.619995,1740.180054,1179500,1740.180054,lose,1746.900024,13.439941
2021-01-15,1756.000000,1721.550049,1738.189941,1736.189941,1328300,1736.189941,lose,1737.189941,2.000000
2021-01-19,1809.275024,1741.459961,1752.250000,1790.859985,1734600,1790.859985,win,1771.554993,38.609985
2021-01-20,1903.709961,1825.530029,1831.459961,1886.900024,2490300,1886.900024,win,1859.179993,55.440063
2021-01-21,1934.859985,1887.109985,1898.000000,1891.250000,2063900,1891.250000,lose,1894.625000,6.750000
2021-01-22,1910.949951,1881.760010,1895.680054,1901.050049,1272100,1901.050049,win,1898.365051,5.369995
2021-01-25,1929.579956,1867.530029,1920.670044,1899.400024,1927300,1899.400024,lose,1910.035034,21.270020
2021-01-26,1925.000000,1884.244995,1888.839966,1917.239990,1313100,1917.239990,win,1903.039978,28.400024
2021-01-27,1890.000000,1809.000000,1882.530029,1830.790039,2748300,1830.790039,lose,1856.660034,51.739990
2021-01-28,1898.829956,1842.640015,1843.939941,1863.109985,1773100,1863.109985,win,1853.524963,19.170044
2021-01-29,1857.280029,1810.199951,1846.170044,1835.739990,1612600,1835.739990,lose,1840.955017,10.430054
2021-02-01,1922.391968,1850.930054,1853.569946,1901.349976,1602200,1901.349976,win,1877.459961,47.780029
2021-02-02,1955.760010,1914.489990,1922.560059,1927.510010,2273700,1927.510010,win,1925.035034,4.949951
2021-02-03,2116.500000,2018.380005,2073.000000,2070.070068,4118200,2070.070068,lose,2071.535034,2.929932
2021-02-04,2078.550049,2042.589966,2068.889893,2062.370117,1851100,2062.370117,lose,2065.630005,6.519775
2021-02-05,2102.510010,2059.330078,2070.000000,2098.000000,1533900,2098.000000,win,2084.000000,28.000000

In [4]:
win = df.index[df.Status == "win"]
lose = df.index[df.Status == "lose"]

middle_win = df.Middle[df.Status == "win"]
middle_lose = df.Middle[df.Status == "lose"]

height_win = df.Height[df.Status == "win"]
height_lose = df.Height[df.Status == "lose"]

for date in win:
    print(date)
print("\n")    
for date in lose:
    print(date)

2021-01-05 00:00:00
2021-01-06 00:00:00
2021-01-07 00:00:00
2021-01-08 00:00:00
2021-01-13 00:00:00
2021-01-19 00:00:00
2021-01-20 00:00:00
2021-01-22 00:00:00
2021-01-26 00:00:00
2021-01-28 00:00:00
2021-02-01 00:00:00
2021-02-02 00:00:00
2021-02-05 00:00:00


2021-01-04 00:00:00
2021-01-11 00:00:00
2021-01-12 00:00:00
2021-01-14 00:00:00
2021-01-15 00:00:00
2021-01-21 00:00:00
2021-01-25 00:00:00
2021-01-27 00:00:00
2021-01-29 00:00:00
2021-02-03 00:00:00
2021-02-04 00:00:00

In [13]:
p = figure(x_axis_type="datetime",width = 1000, height = 300)

# Styling
p.title.text = "Candlestick Chart"
p.grid.grid_line_alpha = 0.3

# segment(heightX,heightY,lowX,lowY)
p.segment(df.index,df.High,df.index,df.Low,color="black")

# p.rect(x,y,width,height)
hours_12 = 12 * 60 * 60 * 1000
p.rect(win,middle_win, hours_12,
       height_win,line_color="black",fill_color="#CCFFFF")

p.rect(lose,middle_lose, hours_12,
        height_lose,line_color="black",fill_color="#FF3333")



output_file('stock_graph.html')

show(p)
#p.quad(top=df['Open'],bottom=df['Close'])